### ISSUE TITLE
Hangs searching sources

### ISSUE THREAD

**Issue by ffsi** [tknorris/salts#124]
In the second part of the search for sources, the failure addon, being necessary to repeat the search several times until loading sources.

Part of the log:

13:24:07 T:8768  NOTICE: Stream All The Sources: Getting Url: http://onlinemovies-pro.com/the-martian-2015/ cookie=|{}| data=|None| extra headers=|{}| (ENCODED)
13:24:07 T:5428   ERROR: EXCEPTION: argument "path" for method "XBMCAddon::xbmcvfs::exists" must be unicode or str
13:24:07 T:5428   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: argument "path" for method "XBMCAddon::xbmcvfs::exists" must be unicode or str
                                            Traceback (most recent call last):
                                              File "C:\Program Files (x86)\Kodi\portable_data\addons\script.common.plugin.cache\default.py", line 40, in <module>
                                                run()
                                              File "C:\Program Files (x86)\Kodi\portable_data\addons\script.common.plugin.cache\default.py", line 35, in run
                                                s.run()
                                              File "C:\Program Files (x86)\Kodi\portable_data\addons\script.common.plugin.cache/lib\StorageServer.py", line 263, in run
                                                if self.xbmcvfs.exists(self.socket):
                                            TypeError: argument "path" for method "XBMCAddon::xbmcvfs::exists" must be unicode or str
                                            -->End of Python script error report<--

13:24:08 T:8504 WARNING: Stream All The Sources: Error (HTTP Error 403: Forbidden) during scraper http get: http://rlssource.net/?s=The+Martian+2015&go=Search
13:24:08 T:1752  NOTICE: Stream All The Sources: Getting Url: http://player.pubfilm.com/smplayer/player.php?link=https://picasaweb.google.com/lh/photo/auth123MTE0OT@pfpMjY4OTEwOTg5MjQxNjkyL1BoaW1tb2k3NzAyP2F1dGhrZXk9!BeL3Yxc1JnQ0lmQ2x2!BeL0k0b2VFdlFFIzYyMzQzMTUyOTIxNzQwNTQzMzg=&sub=aHR0cDovL3BsYXllci5wdWJmaWxtLmNvbS9zdWIvVGhlLk1hcnRpYW4uMjAxNS5zcnQ= cookie=|{}| data=|None| extra headers=|{}| (ENCODED)
13:24:08 T:4800 WARNING: Stream All The Sources: Error (HTTP Error 403: Forbidden) during scraper http get: http://twomovies.us
13:24:08 T:4800  NOTICE: Stream All The Sources: Getting Url: http://twomovies.us/Xajax/aj0001 cookie=|{}| data=|{'xjxargs[]': ['S<![CDATA[The Martian]]>', 'Stitle'], 'xjxfun': 'search_suggest', 'xjxr': '1453821848709'}| extra headers=|{'Referer': 'http://twomovies.us/', 'X-Requested-With': 'XMLHttpRequest', 'User-Agent': 'SALTS for Kodi/1.0.107'}|
13:24:08 T:6304  NOTICE: Stream All The Sources: Service: shutting down...

13:24:15 T:4036 WARNING: Stream All The Sources: Retrying (2/5) SQL: INSERT OR REPLACE INTO url_cache (url,data,response,timestamp) VALUES(?, ?, ?, ?) Error: database is locked
13:24:15 T:4136 WARNING: Previous line repeats 1 times.

13:24:19 T:1968 WARNING: Stream All The Sources: Retrying (2/5) SQL: INSERT OR REPLACE INTO url_cache (url,data,response,timestamp) VALUES(?, ?, ?, ?) Error: database is locked
13:24:20 T:6696 WARNING: Previous line repeats 3 times.

13:24:23 T:308   ERROR: Exception in thread Thread-37:
                                            Traceback (most recent call last):
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\threading.py", line 810, in __bootstrap_inner
                                                self.run()
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\threading.py", line 763, in run
                                                self.__target(*self.__args, **self.__kwargs)
                                              File "C:\Program Files (x86)\Kodi\portable_data\addons\plugin.video.salts\salts_lib\utils.py", line 416, in parallel_get_sources
                                                hosters = scraper.get_sources(video)
                                              File "C:\Program Files (x86)\Kodi\portable_data\addons\plugin.video.salts\scrapers\yifystreaming_scraper.py", line 69, in get_sources
                                                stream_url = link['link']
                                            TypeError: string indices must be integers

**Comment by tknorris** [comment]
To resolve the error you've shown disable yify-streaming scraper.
