### ISSUE TITLE
alluc scraper appears to be broken

### ISSUE THREAD

**Issue by smhc** [tknorris/salts#157]
Log here: http://pastebin.com/LqS3fqpU

Kodi/salts hangs when getting sources unless the alluc scraper is disabled.

Is it possible for SALTS to catch these errors and disable the scraper automatically instead of just hanging the user interface?

**Comment by tknorris** [comment]
If you are running the beta, go to settings->reset base urls to default and it will fix it. If not, manually updating the base url in addon settings for the alluc scraper to http://www.alluc.ee will fix it.

**Comment by smhc** [comment]
I think I updated to the Beta correctly and reset base urls, however there are now exceptions in other scrapers (see below). Is it possible to have exception handling and skip over these failed scraper plugins?



18:14:13 T:2332   ERROR: Exception in thread Thread-31:
                                            Traceback (most recent call last):
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\threading.py", line 810, in __bootstrap_inner
                                                self.run()
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\threading.py", line 763, in run
                                                self.__target(*self.__args, **self.__kwargs)
                                              File "C:\Users\xxxx\AppData\Roaming\Kodi\addons\plugin.video.salts\salts_lib\utils2.py", line 383, in parallel_get_sources
                                                hosters = scraper.get_sources(video)
                                              File "C:\Users\xxxx\AppData\Roaming\Kodi\addons\plugin.video.salts\scrapers\pubfilm_scraper.py", line 88, in get_sources
                                                sources = self.__get_gk_links(match.group(1))
                                              File "C:\Users\xxxx\AppData\Roaming\Kodi\addons\plugin.video.salts\scrapers\pubfilm_scraper.py", line 123, in __get_gk_links
                                                stream_url = link['link']
                                            TypeError: string indices must be integers

**Comment by tknorris** [comment]
It works the way it does for a reason. If that scraper is throwing an exception, just disable it for now.

**Comment by smhc** [comment]
I tried again and it seems to be working ok now.
