### ISSUE TITLE
SALTS fails with "No module named lib" in log

### ISSUE THREAD

**Issue by Sir-Fancy** [tknorris/salts#168]
I'm having some trouble with salts after I updated, and these are the last errors in the kodi log. 

```
16:25:40 1478.773438 T:2804675568   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named lib
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.salts/default.py", line 2398, in <module>
                                                sys.exit(main())
                                              File "/home/osmc/.kodi/addons/plugin.video.salts/default.py", line 2389, in main
                                                url_dispatcher.dispatch(mode, queries)
                                              File "/home/osmc/.kodi/addons/plugin.video.salts/salts_lib/url_dispatcher.py", line 80, in dispatch
                                                self.func_registry[mode](*args, **kwargs)
                                              File "/home/osmc/.kodi/addons/plugin.video.salts/default.py", line 1102, in get_sources
                                                hosters = apply_urlresolver(hosters)
                                              File "/home/osmc/.kodi/addons/plugin.video.salts/default.py", line 1138, in apply_urlresolver
                                                import urlresolver
                                              File "/home/osmc/.kodi/addons/script.module.urlresolver/lib/urlresolver/__init__.py", line 37, in <module>
                                                from plugins import *
                                              File "/home/osmc/.kodi/addons/script.module.urlresolver/lib/urlresolver/plugins/vidlockers.py", line 21, in <module>
                                                from lib import jsunpack
                                            ImportError: No module named lib
                                            -->End of Python script error report<--
16:25:41 1479.703003 T:3024904752   ERROR: GetDirectory - Error getting plugin://plugin.video.salts/<<redacted>>
16:25:41 1479.709106 T:3024904752   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.salts/<<redacted>>) failed
16:25:46 1484.822998 T:2728915952  NOTICE: ES: Client  from 192.168.0.105 timed out
16:27:08 1566.999023 T:2840327152 WARNING: CSkinInfo: failed to load skin settings
16:27:08 1567.353760 T:2840327152   ERROR: EXCEPTION: Non-Existent Control 300
16:27:58 1617.298340 T:2804675568 WARNING: CPythonInvoker(16): Script invoked without an addon. Adding all addon modules installed to python path as fallback. This behaviour will be removed in future version.
```

I'm on a Raspberry Pi B+, let me know if you need more logs.

**Comment by tknorris** [comment]
double check that the plugins/lib folder exists. For some people the install partially completed. If you don't, then delete the .kodi/addons/script.module.urlresolver directory and reinstall the addon.

**Comment by tknorris** [comment]
To be more clear on the plugins/lib folder it should be at .kodi/addons/script.module.urlresolver/lib/urlresolver/plugins/lib

**Comment by Sir-Fancy** [comment]
Didn't see the lib folder so I went ahead and deleted the folder you said and reinstalled SALTS. It didn't reinstall URLResolver however, so how can I do that?

**Comment by tknorris** [comment]
The easiest way is to jsut download and install it from here: https://github.com/tknorris/tknorris-beta-repo/tree/master/zips/script.module.urlresolver

**Comment by Sir-Fancy** [comment]
I'm now getting "Failed to install Add-on from file" when I install script.module.urlresolver-2.10.13~beta6.zip. Doesn't give any reason why in kodi.log. Thanks for the help so far!

**Comment by tknorris** [comment]
that's weird

**Comment by tknorris** [comment]
you did download it by clicking on "View raw" right?

**Comment by Sir-Fancy** [comment]
I just used the URL, that's probably why. Let me try that.

**Comment by tknorris** [comment]
that's just the directory of them, you have to pick the latest zip from that directory and then download it and install it.

**Comment by Sir-Fancy** [comment]
Gotcha. I thought wget would resolve it or something. URLResolver seems to be working, let me try to open a stream.

**Comment by Sir-Fancy** [comment]
Alright SALTS is failing and telling me in the logs that the database is locked. Now what?

**Comment by tknorris** [comment]
post a log. database locked is a normal error if your box is overloaded.

**Comment by Sir-Fancy** [comment]
```
14:58:46 4873.652832 T:2658137072   ERROR: Exception in thread Thread-2:
                                            Traceback (most recent call last):
                                              File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
                                                self.run()
                                              File "/usr/lib/python2.7/threading.py", line 763, in run
                                                self.__target(*self.__args, **self.__kwargs)
                                              File "/home/osmc/.kodi/addons/plugin.video.salts/salts_lib/utils2.py", line 386, in parall
el_get_sources
                                                hosters = scraper.get_sources(video)
                                              File "/home/osmc/.kodi/addons/plugin.video.salts/scrapers/pw_scraper.py", line 62, in get_
sources
                                                html = self._http_get(url, cache_limit=.5)
                                              File "/home/osmc/.kodi/addons/plugin.video.salts/scrapers/scraper.py", line 244, in _http_
get
                                                headers=headers, allow_redirect=allow_redirect, method=method, cache_limit=cache_limit)
                                              File "/home/osmc/.kodi/addons/plugin.video.salts/scrapers/scraper.py", line 325, in _cache
d_http_get
                                                self.db_connection.cache_url(url, html, data)
                                              File "/home/osmc/.kodi/addons/plugin.video.salts/salts_lib/db_utils.py", line 119, in cach
e_url
                                                self.__execute(sql, (url, data, body, res_header, now))
                                              File "/home/osmc/.kodi/addons/plugin.video.salts/salts_lib/db_utils.py", line 496, in __ex
ecute
                                                cur.execute(sql, params)
                                            OperationalError: database is locked
14:58:47 4874.663574 T:2389701616   ERROR: Exception in thread Thread-26:
                                            Traceback (most recent call last):
                                              File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
                                                self.run()
                                              File "/usr/lib/python2.7/threading.py", line 763, in run
                                                self.__target(*self.__args, **self.__kwargs)
                                              File "/home/osmc/.kodi/addons/plugin.video.salts/salts_lib/utils2.py", line 386, in parall
el_get_sources
                                                hosters = scraper.get_sources(video)
                                              File "/home/osmc/.kodi/addons/plugin.video.salts/scrapers/watchfree_scraper.py", line 59,
in get_sources
                                                html = self._http_get(url, cache_limit=.5)
                                              File "/home/osmc/.kodi/addons/plugin.video.salts/scrapers/scraper.py", line 244, in _http_
get
                                                headers=headers, allow_redirect=allow_redirect, method=method, cache_limit=cache_limit)
                                              File "/home/osmc/.kodi/addons/plugin.video.salts/scrapers/scraper.py", line 325, in _cache
d_http_get
                                                self.db_connection.cache_url(url, html, data)
                                              File "/home/osmc/.kodi/addons/plugin.video.salts/salts_lib/db_utils.py", line 119, in cach
e_url
                                                self.__execute(sql, (url, data, body, res_header, now))
                                              File "/home/osmc/.kodi/addons/plugin.video.salts/salts_lib/db_utils.py", line 496, in __ex
:
```

This went on for a while. I'm assuming it's having trouble accessing it since I reinstalled? Is there any way to delete it?

**Comment by tknorris** [comment]
I really need the full log, not just part. Upload it to xbmclogs or pastebin and give me a link here.

**Comment by Sir-Fancy** [comment]
No prob, one moment.

**Comment by Sir-Fancy** [comment]
paste.osmc.io/useciozac

**Comment by tknorris** [comment]
Not Found

**Comment by Sir-Fancy** [comment]
Edited

**Comment by tknorris** [comment]
try restarting kodi.

**Comment by Sir-Fancy** [comment]
...probably should've tried that haha. One moment

**Comment by Sir-Fancy** [comment]
That did it! Thanks for the help! Keep up the great work :)
