### ISSUE TITLE
Unable to play when using Library

### ISSUE THREAD

**Issue by abhinavkssk** [tknorris/salts#93]
Hi,

I'm unable to play any TVShow which were previously added to the library. This started happening after a recent update. The following is the error from the log file 
```
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.Exception'>
                                            Error Contents: Error: mode |get_sources| requested argument |trakt_id| but it was not provided.
                                            Traceback (most recent call last):
                                              File "/home/****/.kodi/addons/plugin.video.salts/default.py", line 2122, in <module>
                                                sys.exit(main())
                                              File "/home/****/.kodi/addons/plugin.video.salts/default.py", line 2116, in main
                                                url_dispatcher.dispatch(mode, queries)
                                              File "/home/****/.kodi/addons/plugin.video.salts/salts_lib/url_dispatcher.py", line 67, in dispatch
                                                raise Exception(message)
                                            Exception: Error: mode |get_sources| requested argument |trakt_id| but it was not provided.
                                            -->End of Python script error report<--
````

This doesn't occur when I'm not playing from the library though. Any fixes?

**Comment by tknorris** [comment]
Refresh your strm files. The format changed slightly from 1.0.0 to 1.0.47
